---
- name: Add bash prompt
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Add prompt for users
      blockinfile:
        marker: '# {mark} custom prompt managed by Ansible #'
        path: /home/{{ user }}/.bashrc
        block: "{{ lookup('ansible.builtin.file', 'files/bash.sh') }}"
      when: user is defined

