---
- name: Add bash prompt
  hosts: localhost
  connection: local
  become: false
  vars:
    root_bash: false
  tasks:
    - name: Add prompt for users
      blockinfile:
        marker: '# {mark} custom prompt managed by Ansible #'
        path: /home/{{ user }}/.bashrc
        block: "{{ lookup('ansible.builtin.file', 'files/bash.txt') }}"
      when: user is defined

    - name: Add prompt for root
      become: true
      blockinfile:
        marker: '# {mark} custom prompt managed by Ansible #'
        path: /root/.bashrc
        block: "{{ lookup('ansible.builtin.file', 'files/root_bash.txt') }}"
      when: root_bash
    
    
